import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { receptionistApi } from '../../api';
import { LoadingSpinner } from '../../components/common/LoadingSpinner';
import { Modal } from '../../components/common/Modal';
import { useToast } from '../../context/ToastContext';
import {
  Users,
  Search,
  UserPlus,
  Phone,
  ArrowRight,
  CheckCircle2,
  Calendar,
  Building,
  UserCheck,
  Filter,
  Stethoscope,
  Sparkles,
  Clock
} from 'lucide-react';

export const ExecutiveLeadsQueuePage = () => {
  const [leads, setLeads] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [doctors, setDoctors] = useState([]);
  const [assignModalLead, setAssignModalLead] = useState(null);
  const [selectedDoctorId, setSelectedDoctorId] = useState('');
  const [assignRemarks, setAssignRemarks] = useState('');
  const [assigning, setAssigning] = useState(false);

  const { showToast } = useToast();
  const navigate = useNavigate();

  const fetchLeads = async () => {
    setLoading(true);
    try {
      const params = {};
      if (statusFilter !== 'all') params.status = statusFilter;
      if (searchTerm.trim()) params.search = searchTerm.trim();
      const res = await receptionistApi.getExecutiveLeads(params);
      if (res.success) {
        setLeads(res.data || []);
      }
    } catch (err) {
      showToast(err.message || 'Failed to fetch executive leads', 'error');
    } finally {
      setLoading(false);
    }
  };

  const fetchDoctors = async () => {
    try {
      const res = await receptionistApi.getActiveDoctors();
      if (res.success) {
        setDoctors(res.data || []);
      }
    } catch (e) {
      // non-blocking
    }
  };

  useEffect(() => {
    fetchLeads();
    fetchDoctors();
  }, [statusFilter]);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    fetchLeads();
  };

  const handleOpenLead = async (lead) => {
    try {
      await receptionistApi.openExecutiveLead(lead.lead_id);
    } catch (e) {
      // non-blocking status touch
    }

    navigate('/receptionist/patients/register', {
      state: {
        initialMobile: lead.mobile_number,
        leadId: lead.lead_id,
        leadSource: 'executive_lead',
        patientName: lead.lead_name,
        age: lead.age,
        gender: lead.gender,
        village: lead.village || lead.mandal,
        reason: lead.campaign || lead.source || 'Call Center Outreach',
      },
    });
  };

  const handleOpenAssignModal = (lead) => {
    setAssignModalLead(lead);
    setSelectedDoctorId('');
    setAssignRemarks('');
  };

  const handleConfirmAssignDoctor = async () => {
    if (!selectedDoctorId) {
      showToast('Please select a doctor to assign', 'warning');
      return;
    }

    setAssigning(true);
    try {
      const res = await receptionistApi.assignExecutiveLeadDoctor(assignModalLead.lead_id, {
        doctor_id: parseInt(selectedDoctorId),
        remarks: assignRemarks
      });

      if (res.success) {
        showToast('Doctor assigned to executive lead successfully', 'success');
        setAssignModalLead(null);
        fetchLeads();
      } else {
        showToast(res.message || 'Failed to assign doctor', 'error');
      }
    } catch (err) {
      showToast(err.message || 'Failed to assign doctor', 'error');
    } finally {
      setAssigning(false);
    }
  };

  const totalLeads = leads.length;
  const newLeadsCount = leads.filter(l => l.status === 'new').length;
  const convertedCount = leads.filter(l => l.status === 'converted').length;
  const assignedCount = leads.filter(l => l.status === 'assigned').length;

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-6 rounded-3xl border border-slate-200 shadow-2xs">
        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <Users className="w-5 h-5 text-purple-600" />
            <span>Call Center Executive Leads Queue</span>
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Incoming patient leads generated by Call Center Executives awaiting Receptionist Doctor Assignment & Intake.
          </p>
        </div>

        {/* Quick Stats Badges */}
        <div className="flex items-center gap-3">
          <div className="bg-purple-50 border border-purple-200 px-3 py-1.5 rounded-xl text-center">
            <div className="text-[10px] uppercase font-bold text-purple-600">New Leads</div>
            <div className="text-sm font-black text-purple-900 font-mono">{newLeadsCount}</div>
          </div>
          <div className="bg-blue-50 border border-blue-200 px-3 py-1.5 rounded-xl text-center">
            <div className="text-[10px] uppercase font-bold text-blue-600">Assigned</div>
            <div className="text-sm font-black text-blue-900 font-mono">{assignedCount}</div>
          </div>
          <div className="bg-emerald-50 border border-emerald-200 px-3 py-1.5 rounded-xl text-center">
            <div className="text-[10px] uppercase font-bold text-emerald-600">Converted</div>
            <div className="text-sm font-black text-emerald-900 font-mono">{convertedCount}</div>
          </div>
        </div>
      </div>

      {/* Filter and Search Controls */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-2xs flex flex-col md:flex-row items-center justify-between gap-4">
        <form onSubmit={handleSearchSubmit} className="relative flex-1 w-full flex items-center gap-2">
          <div className="relative flex-1">
            <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search by Lead ID, Patient Name, Mobile Number, or Executive..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500 transition-all"
            />
          </div>
          <button
            type="submit"
            className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white font-bold text-xs rounded-xl shadow-xs transition-colors cursor-pointer"
          >
            Search
          </button>
        </form>

        <div className="flex items-center gap-2 w-full md:w-auto">
          <Filter className="w-4 h-4 text-slate-400" />
          <span className="text-xs font-semibold text-slate-600">Status:</span>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl font-medium text-slate-700 focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500"
          >
            <option value="all">All Statuses</option>
            <option value="new">New</option>
            <option value="contacted">Contacted</option>
            <option value="interested">Interested</option>
            <option value="assigned">Assigned</option>
            <option value="converted">Converted</option>
          </select>
        </div>
      </div>

      {/* Leads Table */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-2xs overflow-hidden">
        {loading ? (
          <LoadingSpinner label="Loading executive leads queue..." />
        ) : leads.length === 0 ? (
          <div className="p-12 text-center text-slate-500 text-xs">
            <Users className="w-10 h-10 text-slate-300 mx-auto mb-2" />
            No leads found matching current criteria.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                  <th className="py-3.5 px-4">Lead ID & Name</th>
                  <th className="py-3.5 px-4">Contact</th>
                  <th className="py-3.5 px-4">Created By Executive</th>
                  <th className="py-3.5 px-4">Lead Status</th>
                  <th className="py-3.5 px-4">Date Created</th>
                  <th className="py-3.5 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs">
                {leads.map((lead) => (
                  <tr key={lead.lead_id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="py-3.5 px-4">
                      <div className="font-bold text-slate-900">{lead.lead_name}</div>
                      <div className="text-[11px] text-slate-400 font-mono">Lead #{lead.lead_id}</div>
                      {lead.campaign && (
                        <span className="text-[10px] text-slate-500 block truncate max-w-xs">{lead.campaign}</span>
                      )}
                    </td>

                    <td className="py-3.5 px-4 font-mono font-bold text-slate-800">
                      {lead.mobile_number}
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="font-semibold text-slate-800">
                        {lead.executive_name || lead.created_by_name || 'Call Center Exec'}
                      </span>
                      <span className="block text-[10px] text-slate-400 font-mono">
                        {lead.executive_employee_id || 'EXEC'} • Outreach
                      </span>
                    </td>

                    <td className="py-3.5 px-4">
                      <span
                        className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold capitalize ${
                          lead.status === 'converted'
                            ? 'bg-emerald-100 text-emerald-800'
                            : lead.status === 'assigned'
                            ? 'bg-blue-100 text-blue-800'
                            : lead.status === 'interested'
                            ? 'bg-amber-100 text-amber-800'
                            : lead.status === 'contacted'
                            ? 'bg-indigo-100 text-indigo-800'
                            : 'bg-purple-100 text-purple-800'
                        }`}
                      >
                        {lead.status}
                      </span>
                    </td>

                    <td className="py-3.5 px-4 text-slate-500 font-mono text-[11px]">
                      {lead.created_at ? new Date(lead.created_at).toLocaleDateString() : 'Today'}
                    </td>

                    <td className="py-3.5 px-4 text-right">
                      {lead.status !== 'converted' ? (
                        <div className="flex items-center justify-end gap-2">
                          <button
                            onClick={() => handleOpenAssignModal(lead)}
                            className="px-2.5 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded-lg transition-colors cursor-pointer text-[11px] inline-flex items-center gap-1"
                            title="Assign Doctor directly"
                          >
                            <Stethoscope className="w-3.5 h-3.5 text-slate-500" />
                            <span>Assign Doc</span>
                          </button>
                          <button
                            onClick={() => handleOpenLead(lead)}
                            className="px-3.5 py-1.5 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded-lg shadow-sm transition-colors cursor-pointer inline-flex items-center gap-1.5 text-[11px]"
                          >
                            <UserPlus className="w-3.5 h-3.5" />
                            <span>Register / Assign</span>
                          </button>
                        </div>
                      ) : (
                        <div className="text-right">
                          <span className="text-emerald-700 font-semibold text-[11px] inline-flex items-center gap-1">
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            <span>Converted ({lead.converted_registration_id || 'Active'})</span>
                          </span>
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Assign Doctor Modal */}
      {assignModalLead && (
        <Modal
          isOpen={!!assignModalLead}
          onClose={() => setAssignModalLead(null)}
          title={`Assign Doctor to Lead #${assignModalLead.lead_id}`}
        >
          <div className="space-y-4 text-xs">
            <div className="bg-purple-50/70 p-3.5 rounded-xl border border-purple-100 space-y-1">
              <div className="font-bold text-slate-800 text-sm">{assignModalLead.lead_name}</div>
              <div className="text-slate-600 flex items-center gap-2">
                <span>Mobile: <strong className="font-mono">{assignModalLead.mobile_number}</strong></span>
                <span>•</span>
                <span>Executive: <strong>{assignModalLead.executive_name || 'Call Center'}</strong></span>
              </div>
            </div>

            <div>
              <label className="block text-slate-700 font-bold mb-1.5">Select Active Doctor <span className="text-red-500">*</span></label>
              <select
                value={selectedDoctorId}
                onChange={(e) => setSelectedDoctorId(e.target.value)}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500 font-medium"
              >
                <option value="">-- Choose Doctor --</option>
                {doctors.map((doc) => (
                  <option key={doc.doctor_id} value={doc.doctor_id}>
                    Dr. {doc.full_name} ({doc.specialization || 'Consultant'}) - ₹{doc.new_consultation_fee || 500}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-slate-700 font-bold mb-1.5">Assignment Remarks / Instructions</label>
              <textarea
                rows={3}
                value={assignRemarks}
                onChange={(e) => setAssignRemarks(e.target.value)}
                placeholder="Optional notes regarding patient symptoms, scheduled date or preferences..."
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500"
              />
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={() => setAssignModalLead(null)}
                className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold rounded-xl transition-colors cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleConfirmAssignDoctor}
                disabled={assigning}
                className="px-4 py-2 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded-xl shadow-xs transition-colors cursor-pointer flex items-center gap-1.5"
              >
                {assigning ? <LoadingSpinner size="sm" /> : <UserCheck className="w-4 h-4" />}
                <span>Confirm Assignment</span>
              </button>
            </div>
          </div>
        </Modal>
      )}
    </div>
  );
};

